# Site settings
title: Office of Data, Research, and Accountability
email: Billy.Buchanan@fayettte.kyschools.us
description: Data and Coding Standards
baseurl: "/fcps-standards" # Name of the repository
url: "https://wbuchanan.github.io" # the base hostname & protocol for your site
github_username:  fcps

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
